// Login User
export const FETCH_LOGIN_REQUEST_TRIGGERED = 'FETCH_LOGIN_REQUEST_TRIGGERED';
export const FETCH_LOGIN_REQUEST_SUCCESS = 'FETCH_LOGIN_REQUEST_SUCCESS';
export const FETCH_LOGIN_REQUEST_FAILURE = 'FETCH_LOGIN_REQUEST_FAILURE';
// Create User
export const CREATE_USER_REQUEST_TRIGGERED = 'CREATE_USER_REQUEST_TRIGGERED';
export const CREATE_USER_REQUEST_SUCCESS = 'CREATE_USER_REQUEST_SUCCESS';
export const CREATE_USER_REQUEST_FAILURE = 'CREATE_USER_REQUEST_FAILURE';

// Fetch Items by Type
export const FETCH_ITEMS_REQUEST_TRIGGER = 'FETCH_ITEMS_REQUEST_TRIGGER';
export const FETCH_ITEMS_REQUEST_SUCCESS = 'FETCH_ITEMS_REQUEST_SUCCESS';
export const FETCH_ITEMS_REQUEST_FAILURE = 'FETCH_ITEMS_REQUEST_FAILURE';

// Fetch Recent items
export const FETCH_RECENT_ITEMS_REQUEST_TRIGGER = 'FETCH_RECENT_ITEMS_REQUEST_TRIGGER';
export const FETCH_RECENT_ITEMS_REQUEST_SUCCESS = 'FETCH_RECENT_ITEMS_REQUEST_SUCCESS';
export const FETCH_RECENT_ITEMS_REQUEST_FAILURE = 'FETCH_RECENT_ITEMS_REQUEST_FAILURE';
